name: Run Tests

on: [push]

jobs:
    test:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: dotnet test
              run: dotnet test .\src\My.Maui.Responsive.Tests
              shell: pwsh
